server:
  port: 9090


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/root
    username: root
    password: root

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
